services:
  web:
    image: odoo:16.0
    depends_on:
      - postgres
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD_FILE=/run/secrets/db_pass
    volumes:
      # - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
      # - ./logs:/var/log/odoo
    secrets:
      - db_pass
    # command: --config=/etc/odoo/odoo.conf -u test_module -d odoo-test
    command: --config=/etc/odoo/odoo.conf
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_pass
    # - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
      # - ./odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - db_pass
# volumes:
  # odoo-web-data:
  # odoo-db-data:

secrets:
  db_pass:
    file: secrets/pg_pass
